/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/shopping/add-item/{shoppingCartItem}": {
    post: operations["addItemToShoppingCart"];
  };
  "/payments/stripe/webhooks": {
    post: operations["confirmation"];
  };
  "/payments/checkout": {
    post: operations["checkout"];
  };
  "/content/quiz/solution/{contentId}": {
    post: operations["checkSolutionForQuiz"];
  };
  "/content/code/scratch-solution/{contentId}": {
    post: operations["runSolutionFor"];
  };
  "/content/code/code-quiz-solution/{contentId}": {
    post: operations["checkCodeQuizSolutionFor"];
  };
  "/auth/register": {
    post: operations["register"];
  };
  "/auth/refresh": {
    post: operations["refresh"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/auth/force-logout": {
    post: operations["forceLogout"];
  };
  "/sync": {
    get: operations["sync"];
  };
  "/shopping/restore-shopping-cart": {
    get: operations["restoreShoppingCart"];
  };
  "/shopping/available-shopping-items": {
    get: operations["getAvailableShoppingItems"];
  };
  "/payments": {
    get: operations["getPreviousPayments"];
  };
  "/content/my-content-bundles": {
    get: operations["getMyContentBundles"];
  };
  "/content/my-content-bundles/separated": {
    get: operations["getMyContentBundlesSeparated"];
  };
  "/shopping/delete-item/{shoppingCartItem}": {
    delete: operations["removeItemFromShoppingCart"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    MinimalContentBundleResponse: {
      includedContent?: components["schemas"]["MinimalContentResponse"][];
    };
    MinimalContentResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      /** @enum {string} */
      contentType?: "CODING" | "VIDEO" | "QUIZ";
    };
    ShoppingCartResponse: {
      shoppingItems?: components["schemas"]["ShoppingItemResponse"][];
    };
    ShoppingItemResponse: {
      /** Format: int32 */
      id?: number;
      title?: string;
      /** Format: double */
      price?: number;
      contentBundle?: components["schemas"]["MinimalContentBundleResponse"];
    };
    PaymentRequest: {
      successUrl?: string;
      cancelUrl?: string;
    };
    QuizSolutionRequest: {
      solutions: {
        [key: string]: number;
      };
    };
    IncorrectQuizSolutionResponse: {
      /** Format: int32 */
      incorrectQuestionId?: number;
      /** Format: int32 */
      incorrectSolutionSent?: number;
      /** Format: int32 */
      correctSolution?: number;
    };
    QuizSolutionResponse: {
      correctAnswerQuestionIds?: number[];
      incorrectSolutions?: components["schemas"]["IncorrectQuizSolutionResponse"][];
    };
    CodeSolutionRequest: {
      code: string;
    };
    CodeSolutionResponse: {
      results?: components["schemas"]["TestCaseOutcomeResponse"][];
      /** @enum {string} */
      overallResult?: "ALL_PASSED" | "TESTCASES_FAILED";
    };
    TestCaseOutcomeResponse: {
      expected?: string;
      actual?: string;
      /** @enum {string} */
      outcome?: "PASSED" | "FAILED";
      hints?: string[];
    };
    CodeQuizSolutionRequest: {
      solutionsByIndex: {
        [key: string]: string;
      };
    };
    CodeQuizSolutionResponse: {
      correctAnswerIndices?: number[];
      incorrectSolutions?: components["schemas"]["IncorrectCodeQuizSolutionResponse"][];
    };
    IncorrectCodeQuizSolutionResponse: {
      /** Format: int32 */
      incorrectSolutionIndex?: number;
      incorrectAnswer?: string;
      correctSolution?: string;
    };
    RegisterRequest: {
      username: string;
      password: string;
    };
    RefreshTokenRequest: {
      refreshToken: string;
    };
    RefreshTokenResponse: {
      accessToken?: string;
      refreshToken?: string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    LoginResponse: {
      accessToken?: string;
      refreshToken?: string;
    };
    GetAvailableShoppingItemsResponse: {
      shoppingItems?: components["schemas"]["ShoppingItemResponse"][];
    };
    ContentBundleResponse: {
      includedContent?: components["schemas"]["ContentResponse"][];
    };
    ContentResponse: {
      name?: string;
      /** @enum {string} */
      contentType?: "CODING" | "VIDEO" | "QUIZ";
    };
    PaymentResponse: {
      /** Format: double */
      pricePayed?: number;
      boughtContentBundles?: components["schemas"]["ContentBundleResponse"][];
    };
    PreviousPaymentsResponse: {
      previousPayments?: components["schemas"]["PaymentResponse"][];
    };
    MyContentBundlesResponse: {
      contentBundles?: components["schemas"]["ContentBundleResponse"][];
    };
    CodingContentResponse: {
      name?: string;
      /** @enum {string} */
      contentType?: "CODING" | "VIDEO" | "QUIZ";
      /** Format: int32 */
      id?: number;
      description?: string;
      codeSkeleton?: string[];
      codeSnippets?: string[];
      testCases?: components["schemas"]["TestCaseResponse"][];
      /** @enum {string} */
      codingContentType?: "SCRATCH" | "DRAG_AND_DROP" | "FILL_THE_GAP";
    };
    MyContentBundlesSeparatedResponse: {
      contentBundles?: components["schemas"]["SeparatedContentBundleResponse"][];
    };
    QuizContentResponse: {
      name?: string;
      /** @enum {string} */
      contentType?: "CODING" | "VIDEO" | "QUIZ";
      /** Format: int32 */
      id?: number;
      questions?: components["schemas"]["QuizQuestionResponse"][];
    };
    QuizQuestionResponse: {
      /** Format: int32 */
      id?: number;
      question?: string;
      answers?: string[];
      /** Format: int32 */
      solutionIndex?: number;
      solutionChar?: string;
    };
    SeparatedContentBundleResponse: {
      includedVideos?: components["schemas"]["VideoContentResponse"][];
      includedCodings?: components["schemas"]["CodingContentResponse"][];
      includedQuizzes?: components["schemas"]["QuizContentResponse"][];
    };
    TestCaseResponse: {
      input?: string;
      expectedOutput?: string;
    };
    VideoContentResponse: {
      name?: string;
      /** @enum {string} */
      contentType?: "CODING" | "VIDEO" | "QUIZ";
      description?: string;
      resourceUrl?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  addItemToShoppingCart: {
    parameters: {
      path: {
        shoppingCartItem: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ShoppingCartResponse"];
        };
      };
    };
  };
  confirmation: {
    parameters: {
      header: {
        "Stripe-Signature": string;
      };
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  checkout: {
    parameters: {
      query: {
        paymentRequest: components["schemas"]["PaymentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  checkSolutionForQuiz: {
    parameters: {
      path: {
        contentId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuizSolutionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["QuizSolutionResponse"];
        };
      };
    };
  };
  runSolutionFor: {
    parameters: {
      path: {
        contentId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeSolutionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CodeSolutionResponse"];
        };
      };
    };
  };
  checkCodeQuizSolutionFor: {
    parameters: {
      path: {
        contentId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeQuizSolutionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CodeQuizSolutionResponse"];
        };
      };
    };
  };
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  refresh: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["RefreshTokenResponse"];
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  forceLogout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  sync: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  restoreShoppingCart: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ShoppingCartResponse"];
        };
      };
    };
  };
  getAvailableShoppingItems: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["GetAvailableShoppingItemsResponse"];
        };
      };
    };
  };
  getPreviousPayments: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PreviousPaymentsResponse"];
        };
      };
    };
  };
  getMyContentBundles: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MyContentBundlesResponse"];
        };
      };
    };
  };
  getMyContentBundlesSeparated: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MyContentBundlesSeparatedResponse"];
        };
      };
    };
  };
  removeItemFromShoppingCart: {
    parameters: {
      path: {
        shoppingCartItem: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ShoppingCartResponse"];
        };
      };
    };
  };
}
